### ISSUE TITLE
Bad Apostrophes Interpretation

### ISSUE THREAD

**Issue by bokay** [DynamoMTL/dynamo-ops#54]
Apostrophes are interpreted as `â€™` instead of `'`.

Example: http://dna.godynamo.com/categories/guiding-principles/core-values/
However, the issue does not appear locally.

**Comment by DanielWright** [comment]
I think we're failing to set the character-encoding of the page.

**Comment by bokay** [comment]
Thank you very much @DanielWright, nice catch 💥
